[tool.poetry]
name = "pyegsnrc"
version = "0.1.0"
description = ""
authors = []
packages = [{ include = "pyegsnrc", from = "prototyping" }]

[tool.poetry.dependencies]
python = "^3.8"
typing-extensions = "*"
jax = "*"
jaxlib = "*"
matplotlib = "*"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
mypy = "*"
rope = "*"
pylint = "*"
pytest = "*"

[tool.poetry.scripts]
pymedphys = "pyegsnrc.__main__:main"
